name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test PHP ${{ matrix.php }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
        os: ['ubuntu-latest']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: composer diagnose || true
      - run: composer install
      - run: composer audit
      - run: composer run lint
      - run: composer run test
      - name: Test & publish code coverage
        if: ${{ matrix.php == '8.3' && matrix.os == 'ubuntu-latest' }}
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
        with:
          coverageLocations: ${{ github.workspace }}/build/logs/clover.xml:clover
